CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL ,
    email VARCHAR(255) NOT NULL UNIQUE ,
    senha_hash VARCHAR(255) NOT NULL ,
    data_nascimento DATE NOT NULL ,
    faixa_etaria varchar (255)
);

